# Generated by Django 3.2.5 on 2021-07-31 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(max_length=130, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
                ('status', models.BooleanField(default='True')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.catagory')),
            ],
            managers=[
                ('acceptpost', django.db.models.manager.Manager()),
            ],
        ),
    ]
